<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create post</title>
</head>
<body>
<form action="/paper/create" method="post">
    <input type="text" name="title" placeholder="Введите название поста">
    <input type="text" name="description" placeholder="Введите контент поста">
    <input type="submit" name="Создать">
</form>
</body>
</html>